export const FETCH_LIST_TRANSACTIONS = 'FETCH_LIST_TRANSACTIONS';
export const FETCH_LIST_TRANSACTIONS_FAILED = 'FETCH_LIST_TRANSACTIONS_FAILED';
export const FETCH_LIST_TRANSACTIONS_SUCCESS = 'FETCH_LIST_TRANSACTIONS_SUCCESS';

export const FETCH_TRANSACTION = 'FETCH_TRANSACTION';
export const FETCH_TRANSACTION_FAILED = 'FETCH_TRANSACTION_FAILED';
export const FETCH_TRANSACTION_SUCCESS = 'FETCH_TRANSACTION_SUCCESS';

export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const ADD_TRANSACTION_FAILED = 'ADD_TRANSACTION_FAILED';
export const ADD_TRANSACTION_SUCCESS = 'ADD_TRANSACTION_SUCCESS';

export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const UPDATE_TRANSACTION_FAILED = 'UPDATE_TRANSACTION_FAILED';
export const UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS';

export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const DELETE_TRANSACTION_FAILED = 'DELETE_TRANSACTION_FAILED';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';

export const UPDATE_TRANSACTION_STATUS = 'UPDATE_TRANSACTION_STATUS';
export const UPDATE_TRANSACTION_STATUS_FAILED = 'UPDATE_TRANSACTION_STATUS_FAILED';
export const UPDATE_TRANSACTION_STATUS_SUCCESS = 'UPDATE_TRANSACTION_STATUS_SUCCESS';

export const SET_FILTER_VALUE = 'SET_FILTER_VALUE';



 